### ISSUE TITLE
hydroxyl hydrogens correction 

### ISSUE THREAD

**Issue by kexul** [openforcefield/openforcefields#16]
Hi, in the paper 'Escaping Atom Types in Force Fields Using Direct Chemical Perception', the author mentioned that `AMBER-family force field hydroxyl hydrogens are known to have an issue when brought in close proximity where they can "fuse" in some situations.` and they made some correction in the SMIRNOFF forcefield, had that been fixed in the newly published `Parsley` forcefield?

**Comment by j-wags** [comment]
Hi @kexul,

@davidlmobley has been here longer than me, so he should verify this answer. But my quick assessment is that the hydroxyl hydrogen in GAFF has 0 radius and 0 well depth, as seen in [this copy of the GAFF 1.81 `gaff.dat`](https://github.com/rsdefever/GAFF-foyer/blob/master/gafffoyer/gaffparms/gaff.dat#L7128). 

The progression of force fields in OpenFF started with [the smirnoff99Frosst line of force fields](https://github.com/openforcefield/smirnoff99Frosst), where we didn't attempt any numerical fitting or performance improvement, we just did debugging of certain things by hand. The hydroxyl hydrogen radius was indeed initially set to 0. It looks like, between version [1.0.6](https://github.com/openforcefield/smirnoff99Frosst/blob/v1.0.6/smirnoff99Frosst/smirnoff99Frosst.ffxml#L319) and [1.0.7](https://github.com/openforcefield/smirnoff99Frosst/blob/v1.0.7/smirnoff99Frosst/smirnoff99Frosst.offxml#L315), the hydroxyl hydrogen radius was set to a small-but-nonzero value. 

We have kept that small-but-nonzero value to this day, and it is still present in [our most recent force field release (openff-1.2.0)](https://github.com/openforcefield/openforcefields/blob/master/openforcefields/offxml/openff-1.2.0.offxml#L330). We anticipate doing numerical refitting of these vdW parameters in the next few months, so we will probably make a new FF release with this radius changed in late 2020.

**Comment by davidlmobley** [comment]
Yes, this was fixed in `smirnoff99Frosst` and remains fixed. We have not yet re-fit those LJ radii, so they are still what they were in `smirnoff99Frosst`, but for OpenFF 2.0 they may be re-fit so they might change. Still, we plan for them to remain nonzero, as having them be nonzero is critical.

Marking this as closed, but feel free to reopen if you have an issue or need more info.
